---
- name: Configure Domain Controller
  hosts: role_domain_controller
  become: false
  gather_facts: false

  vars:
    ansible_host: "{{ public_ip_address }}"
    ansible_user: ec2-user
    ansible_password: "{{ ec2_admin_password }}"
    ansible_winrm_transport: credssp

  vars_files:
    - vars/domain_config.yml
    - vars/secrets.yml

  tasks:
    - name: Configure domain controller
      ansible.builtin.include_tasks:
        file: tasks/domain_config.yml

    - name: Import handlers
      ansible.builtin.import_tasks:
        file: handlers/domain_config.yml
